# Generated by Django 5.0.6 on 2024-12-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('eventTitle', models.CharField(max_length=255)),
                ('eventSector', models.CharField(max_length=255)),
                ('eventArea', models.CharField(max_length=255)),
                ('eventCriticality', models.IntegerField()),
                ('eventPriority', models.IntegerField()),
                ('eventDescription', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Chamado',
                'verbose_name_plural': 'Chamados',
            },
        ),
    ]
