# Generated by Django 5.0.6 on 2025-01-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='eventCriticalityColor',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chamado',
            name='eventType',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
