# Generated by Django 5.0.6 on 2025-02-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0003_chamado_eventclosedesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='eventFinalStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chamado',
            name='eventCloseDesc',
            field=models.CharField(blank=False, max_length=2000),
        ),
    ]
