# Generated by Django 5.0.6 on 2025-02-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0004_chamado_eventfinalstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='eventFinalStatus',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
