# Generated by Django 5.0.6 on 2025-02-21 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0005_alter_chamado_eventfinalstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamado',
            name='eventCloseDesc',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
