# Generated by Django 5.0.6 on 2025-05-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0009_category_alter_question_question_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_theme',
        ),
    ]
