# Generated by Django 5.0.6 on 2025-05-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0010_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
    ]
