# Generated by Django 5.0.7 on 2025-06-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0011_answers_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(max_length=255),
        ),
    ]
