# Generated by Django 5.0.6 on 2025-05-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0011_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_nickname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
