# Generated by Django 5.0.6 on 2025-05-16 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0012_users_user_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_nickname',
            new_name='user_alias',
        ),
    ]
