# Generated by Django 5.0.7 on 2025-06-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0012_alter_question_answer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
