# Generated by Django 5.0.6 on 2025-05-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamados', '0013_rename_user_nickname_users_user_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
    ]
